apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlsfs
  labels:
    type: statefulsets
    app: mysql-sfs
    env: practice
  namespace: ns-bg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql-sfs
      type: pod
      env: practice
  serviceName: mysql-sfs-svc
  template:
    metadata:
      labels:
        app: mysql-sfs
        type: pod
        env: practice
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:8.0.12
        command: 
        - /bin/bash
        args:
        - -c
        - >-
          /entrypoint.sh
          --server_id=$((20 +  $(echo $HOSTNAME | grep -o '[^-]*$') + 1))
          --report-host=${HOSTNAME}.mysql-sfs-svc.ns-bg.svc.cluster.local
          --binlog-checksum=NONE
          --enforce-gtid-consistency=ON
          --gtid-mode=ON
          --default-authentication-plugin=mysql_native_password
          --log_bin
          --log_slave_updates=ON
          --master_info_repository=TABLE
          --relay_log_info_repository=TABLE
          --transaction_write_set_extraction=XXHASH64
          --skip-host-cache
          --user=mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-sfs-secret
              key: password
        - name: MYSQL_ROOT_HOST
          value: '%'
        ports:
        - name: mysql
          containerPort: 3306
        - name: mysqlx
          containerPort: 33060
        - name: xcom
          containerPort: 33061
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      labels:
        app: mysql-sfs
        type: pvc
        env: practice
    spec:
      storageClassName: azurefile
      volumeMode: Filesystem
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
 

        #  command: 
        # - /bin/bash
        # args:
        # - -c
        # - >-
        #   /entrypoint.sh
        #   --server_id=$((20 +  $(echo $HOSTNAME | grep -o '[^-]*$') + 1))
        #   --report-host=${HOSTNAME}.mysql-sfs-svc.ns-bg.svc.cluster.local
        #   --binlog-checksum=NONE
        #   --enforce-gtid-consistency=ON
        #   --gtid-mode=ON
        #   --default-authentication-plugin=mysql_native_password
        #   --log_bin
        #   --log_slave_updates=ON
        #   --master_info_repository=TABLE
        #   --relay_log_info_repository=TABLE
        #   --transaction_write_set_extraction=XXHASH64
        #   --skip-host-cache