apiVersion: v1
kind: Secret
metadata:
  name: mysql-router-secret
  labels:
    type: secret
    app: mysql-router
    env: practice
  namespace: ns-bg
type: Opaque
stringData:
  password: "passwd"